<?php
// en lang variables
DEFINE('_imgmanager_desc','Image Manager');
DEFINE('_imgmanager_dir','Directory');
DEFINE('_imgmanager_dirUp','Directory Up');
DEFINE('_imgmanager_newFolder','New Folder');
DEFINE('_imgmanager_del','Delete');
DEFINE('_imgmanager_edit','Edit');
DEFINE('_imgmanager_view','View');
DEFINE('_imgmanager_align','Align');
DEFINE('_imgmanager_align_desc','Positioning of the Image');
DEFINE('_imgmanager_width','Width');
DEFINE('_imgmanager_height','Height');
DEFINE('_imgmanager_maxheight','Max Height');
DEFINE('_imgmanager_maxwidth','Max Width');
DEFINE('_imgmanager_constrain','Constrain Proportions');
DEFINE('_imgmanager_image','Image');
DEFINE('_imgmanager_resize_upload','Resize?');
DEFINE('_imgmanager_upload','Upload');
DEFINE('_imgmanager_refresh','Refresh');
DEFINE('_imgmanager_reset','Reset');
DEFINE('_imgmanager_ok','OK');
DEFINE('_imgmanager_cancel','Cancel');
DEFINE('_imgmanager_noImages','No Images Found');
DEFINE('_imgmanager_invalidDir','Invalid base directory');
DEFINE('_imgmanager_vspace','VSpace');
DEFINE('_imgmanager_hspace','HSpace');
DEFINE('_imgmanager_border','Border');
DEFINE('_imgmanager_properties','Image Properties');
DEFINE('_imgmanager_options','Optional Settings');
DEFINE('_imgmanager_alt2','Title');
DEFINE('_imgmanager_onmousemove','Alternative image');
DEFINE('_imgmanager_includeWidth','Include Width');
DEFINE('_imgmanager_includeHeight','Include Height');
DEFINE('_imgmanager_mouseover','mouse over');
DEFINE('_imgmanager_mouseout','mouse out');
DEFINE('_imgmanager_thumbPopup','Thumbnail->Popup');
DEFINE('_imgmanager_popupThumb','Popup Thumbnail');
DEFINE('_imgmanager_thumbCaption','Thumbnail Caption');
//Editor Lang variables
DEFINE('_imgmanager_nogif','GIF format is not supported, image editing not supported.');
DEFINE('_imgmanager_startX','Start X');
DEFINE('_imgmanager_startY','Start Y');
DEFINE('_imgmanager_flip','Flip Image');
DEFINE('_imgmanager_flipVert','Flip Vertical');
DEFINE('_imgmanager_flipHoriz','Flip Horizontal');
DEFINE('_imgmanager_rotate180','Rotate 180 &deg);');
DEFINE('_imgmanager_rotate90CW','Rotate 90 &deg); CW');
DEFINE('_imgmanager_rotate90CCW','Rotate 90 &deg); CCW');
DEFINE('_imgmanager_angle','Angle');
DEFINE('_imgmanager_filename','Filename');
DEFINE('_imgmanager_format','Image Format');
DEFINE('_imgmanager_quality','Quality');
DEFINE('_imgmanager_crop','Crop');
DEFINE('_imgmanager_resize','Resize');
DEFINE('_imgmanager_rotate','Rotate');
DEFINE('_imgmanager_measure','Measure');
DEFINE('_imgmanager_marker','Marker');
DEFINE('_imgmanager_save','Save');
DEFINE('_imgmanager_clear','Clear');

DEFINE('_imgmanager_align_default','Default');
DEFINE('_imgmanager_align_baseline','Baseline');
DEFINE('_imgmanager_align_top','Top');
DEFINE('_imgmanager_align_middle','Middle');
DEFINE('_imgmanager_align_bottom','Bottom');
DEFINE('_imgmanager_align_texttop','TextTop');
DEFINE('_imgmanager_align_absmiddle','Absolute Middle');
DEFINE('_imgmanager_align_absbottom','Absolute Bottom');
DEFINE('_imgmanager_align_left','Left');
DEFINE('_imgmanager_align_right','Right');
?>